name: Build RAM

on:
  push:
    branches: [ "master", "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup NuGet
      uses: nuget/setup-nuget@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Packages
      run: nuget restore "RBX Alt Manager.sln"

    - name: Fix Package Paths
      shell: powershell
      run: |
        $target = "${{ github.workspace }}\packages"
        if (-not (Test-Path $target)) { New-Item -ItemType Directory -Path $target }
        Get-ChildItem -Path "${env:USERPROFILE}\.nuget\packages" -ErrorAction SilentlyContinue | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination $target -Recurse -Force -ErrorAction SilentlyContinue
        }

    - name: Build Solution
      run: msbuild "RBX Alt Manager.sln" /p:Configuration=Release /p:Platform="x86"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RBX-Alt-Manager-Modified
        path: |
          **/bin/x86/Release/
          **/bin/Release/
